### ISSUE TITLE
Fandi Custom wrap

### ISSUE THREAD

**Issue by FandiMohammed** [saesrpgmta/donation-vehicle-shaders#505]
**Vehicle ID** 

400
541
415
**Wrap access**

Fandi123_11
Fandi123_12
Fandi123_13
**Thread for reward change**

**Translations**

**Wrap image**

![193710544-0cad381c-596f-490a-90ba-5f9a6842cbc6 (1)](https://user-images.githubusercontent.com/104403749/209020868-375b5fee-5116-433f-9684-6c373ce751ff.png)
![181396641-33e3b891-c2d6-444b-998c-42584d059131 (2)](https://user-images.githubusercontent.com/104403749/209020987-5d28f198-34bd-44f0-86f7-38fd23c3cfa1.png)
![02002](https://user-images.githubusercontent.com/104403749/209021143-bde19466-b911-42be-96a8-2425bb0e299f.jpg)

**Comment by saesrpg** [comment]
Moved to https://saesrpg.uk/issues/donation-wraps/fandi-custom-wrap-r1/
